### PR TITLE
Angular v6 with RxJS v6

### PR DESCRIPTION
**Pull request by kamilkisiela**
Package | Version | Released
--- | --- | ---
apollo-angular | `1.1.0-rc.0` | May 09 2018 15:39
apollo-angular-link-http-common | `1.1.0-rc.0` | May 09 2018 15:39
apollo-angular-link-http | `1.1.0-rc.0` | May 09 2018 15:39
apollo-angular-link-http-batch | `1.1.0-rc.0` | May 09 2018 15:39
apollo-angular-link-persisted | `1.0.0-beta.1` | May 09 2018 15:39
apollo-angular-link-headers | `1.1.0-rc.0` | May 09 2018 15:39
apollo-angular-cache-ngrx | `1.0.0-beta.1` | May 09 2018 15:39

All have been released with `next` tag, so `yarn add apollo-angular@next` will work.

### CODE REVIEW

**Comment by goldenbearkin** [comment]
so exciting!!! when is this gonna merge?

**Comment by maapteh** [comment]
Nice work so far, can't wait to use it!

**Comment by kamilkisiela** [comment]
An update. I released new versions that supports angular 6. Go try it out and give me some feedback!!1one

**Comment by bardiel** [comment]
So far, so good:
```
├─ apollo-angular-link-http-common@1.1.0-rc.0
├─ apollo-angular-link-http@1.1.0-rc.0
│  └─ apollo-angular-link-http-common@~1.1.0-rc.0
├─ apollo-angular@1.1.0-rc.0
├─ apollo-cache-inmemory@1.2.1
│  ├─ apollo-cache@^1.1.8
│  ├─ apollo-utilities@^1.0.12
├─ apollo-cache@1.1.8
│  └─ apollo-utilities@^1.0.12
├─ apollo-client@2.3.1
│  ├─ apollo-cache@^1.1.8
│  ├─ apollo-link-dedup@^1.0.0
│  ├─ apollo-link@^1.0.0
│  ├─ apollo-utilities@^1.0.12
├─ apollo-link-dedup@1.0.9
│  └─ apollo-link@^1.2.2
├─ apollo-link@1.2.2
│  ├─ apollo-utilities@^1.0.0
├─ apollo-utilities@1.0.12
│  └─ apollo-utilities@^1.0.12
```

**Comment by kamilkisiela** [comment]
@bardiel I noticed that you have `apollo-angular-link-http-common` installed directly in your app, you don't have too, `apollo-angular-link-http` takes care of that. 

Glad to hear it works without any issues :)

**Comment by plinionaves** [comment]
Thank you for nice job @kamilkisiela!
I'm currently recording a course about Angular + GraphQL, do you have any expected date for the final version?
Hug!

**Comment by kamilkisiela** [comment]
@plinionaves probably day or two.

**Comment by plinionaves** [comment]
Wow, great @kamilkisiela!
I will await then, thank you so much for the fast feedback!

**Pull request merged**
