### PR TITLE
Angular 9

### PR DESCRIPTION
**Pull request by kamilkisiela**
```
apollo-angular@next

apollo-angular-link-http@next
apollo-angular-link-http-batch@next
apollo-angular-link-http-common@next

apollo-angular-link-persisted@next
apollo-angular-boost@next
apollo-angular-link-headers@next
```

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@flobacher 

**Doing:**
```json
"enableIvy": false
```

**Means:**
Hey Angular, I don't want to ship a bundle compiled with ngc (Angular Ivy Compiler).

**Why:**
Angular libraries should be shipped as normal and an Angular application should compile it locally with ngc. Take a look at Angular docs or their github or even do `$ ng new demo` and then `$ ng g lib data` and take a look at `tsconfig.lib.prod.json`.

It's not the first time I ship Angular 9 and Ivy. We use Angular 9 and Ivy in our big clients with current apollo-angular (v1.8.0) without any issues, all the Angular 8 libraries are compatible with Angular 9 and Ivy. I do this PR just because you guys want to have Angular 9 in peerDependencies.

**Comment by flobacher** [comment]
Thanks for the explanation!

**Comment by kamilkisiela** [comment]
@flobacher did you test it?

**Comment by flobacher** [comment]
I also already use it without issue in an Angular 9 ivy project, and I trust your statement that you don't have any issues with it

**Comment by flobacher** [comment]
But i can test with this new version, to be sure..

**Comment by wSedlacek** [comment]
Version Tested:
```
    "apollo-angular": "1.9.0-alpha.0",
    "apollo-angular-link-http": "1.10.0-alpha.0",
```

Very nice to see all the install warnings go away.
At this time my use case is pretty simple. Just a standard query.
Everything seems to be working fine with that.
Are there any thing in particular we want to test with version 1.9.0? (Mutations, Caches, etc.)

Is there a roadmap for version 2.0?
I noticed there was a PR(#1380) and issue(#1383) for it but not any progress in a while.
What will it take to get that done and is there anything I can help with?

**Comment by kamilkisiela** [comment]
There are no changes in code, I just want to know if Angular Compiler does or does not scream :) 

About the progress. Once the `@apollo/client` become stable, we will get a stable `apollo-angular`. I don't update anything in the PR because there's no point now.

**Comment by wSedlacek** [comment]
Awesome! That's what I wanted to know!

I will test the alpha versions some more with mutations etc. and keep you posted if any errors come up. So far everything works the same as on v1.8.0 for me.

**Comment by flobacher** [comment]
@kamilkisiela I included `apollo-angular-link-http@next` and `apollo-angular@next` in our project and experienced no issues

**Comment by celvin** [comment]
I've upgraded apollo-angular to next and also graphql to ^15.0.0 and started to emit this error:

`ERROR in node_modules/apollo-client/core/watchQueryOptions.d.ts:56:32 - error TS2315: Type 'ExecutionResult' is not generic.

56     refetchQueries?: ((result: ExecutionResult<T>) => RefetchQueryDescription) | RefetchQueryDescription;
                                  ~~~~~~~~~~~~~~~~~~
node_modules/apollo-client/core/LocalState.d.ts:40:23 - error TS2315: Type 'ExecutionResult' is not generic.

40         remoteResult: ExecutionResult<TData>;
                         ~~~~~~~~~~~~~~~~~~~~~~
node_modules/apollo-client/core/LocalState.d.ts:44:17 - error TS2315: Type 'ExecutionResult' is not generic.

44     }): Promise<ExecutionResult<TData>>;
                   ~~~~~~~~~~~~~~~~~~~~~`

**Comment by kamilkisiela** [comment]
@celvin those are related to `apollo-client` and probably `apollo-link` (which I [fixed](https://github.com/apollographql/apollo-link/pull/1263)), nothing really I can do in `apollo-angular`. My library supports GraphQL v15.

**Pull request merged**
