### PR TITLE
Fixed type definition for subscribe

### PR DESCRIPTION
**Pull request by intellix**
### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Try to include the Pull Request inside of CHANGELOG.md

According to apollo-client it returns a FetchResult<T> whereas apollo-angular says it's an any: https://github.com/apollographql/apollo-client/blob/7eaf4132cd2cd6244260777799406aaa03fcf377/packages/apollo-client/src/ApolloClient.ts#L355

### CODE REVIEW

**Comment by intellix** [comment]
@kamilkisiela any idea why the above 2 checks aren't finishing after days?

**Comment by kamilkisiela** [comment]
@intellix could you rebase?

**Comment by intellix** [comment]
Rebased @kamilkisiela

**Comment by kamilkisiela** [comment]
Thank you @intellix !! 🚀 🥇

**Comment by kamilkisiela** [comment]
[v1.7.0](https://github.com/apollographql/apollo-angular/releases/tag/v1.7.0)

**Comment by PowerKiKi** [comment]
I think this is a breaking change that should have been release as a major version. It would typically break the following code:

```ts

export interface Login {
  login: boolean;
}

this.apollo.mutate<Login>({
    mutation: loginMutation,
    variables: loginData,
}).pipe(map(({data: {login}}) => login));
```

With an error similar to:

```
error TS2339: Property 'login' does not exist on type 'Login | null | undefined'.
```

This is because ultimately `ExecutionResult` is defined with a nullable data property in `graphql` package. So all existing mutations must be adapted accordingly.

I am not sure why data is nullable though, I believe in the context of apollo-angular (not graphql), a mutation either succeeds and its data is exactly as defined in the mutation itself  (probably often non-nullable), or the mutation fails and it goes through the observable error mechanism. But we should never force a mutation result to be nullable... or should we ?

**Comment by PowerKiKi** [comment]
@intellix @kamilkisiela do you have any thoughts on my comment ?

As is it is pretty much impossible to use `strictNullChecks` in combinaison with this PR.

**Comment by PowerKiKi** [comment]
I digged deeper in this issue and finally figured out the issue is in `apollo-client`. For details see https://github.com/apollographql/apollo-client/issues/5662

**Pull request merged**
