### PR TITLE
fix(aot, npm5): resolve AOT issues, add compatibility with npm5

### LINKED ISSUE #340: Problem with AOT
I get an typing error with missing ClientMap when I am compiling via AOT (since I updated from angular2-apollo to apollo-angular). 

ERROR in [at-loader] ./compiled/node_modules/apollo-angular/build/src/Apollo.ngsummary.ts:19:86
    TS2339: Property 'ClientMap' does not exist on type 'typeof "node_modules/apollo-angular/build/src/types"'.

Could you provide me, some workarounds ? 

My Webpack config is the same like in the angular-class bootstrap code. 

Cheers,
Christoph

### LINKED ISSUE #363: bug(aot): warning compiling with AOT in angular v5
When compiling a project using apollo-angular with angular v5 and AOT, the following error is received:

```
apollo-angular/build/src/Apollo.d.ts: (?). This will become an error in Angular v5.x
```

### PR DESCRIPTION
**Pull request by CaerusKaru**
- Add Inject token to the Apollo class constructor to resolve AOT
- Expose types in index.ts
- Fixes #363 
- Fixes #340 
- Closes #360 
- Closes #362

### CODE REVIEW

**Comment by kamilkisiela** [comment]
I just checked if the recent changes allow to use `apollo-angular` with Angular 5's AoT. It seems that it works fine.

It's published as `kamilkisiela-apollo-angular` a not under `apollo-angular` until I do more tests.

Does my release works for you too?

**Comment by CaerusKaru** [comment]
@kamilkisiela The latest release does not resolve #363

**Comment by kamilkisiela** [comment]
@CaerusKaru Example app with AoT, Angular 5 and the `master` branch of `apollo-angular` published as `kamilkisiela-apollo-angular` 

https://github.com/kamilkisiela/apollo-angular-reproduction/tree/aot-5.0.0

**Comment by CaerusKaru** [comment]
@kamilkisiela On fresh install, I get the exact same warning as in #363:

`Warning: Can't resolve all parameters for Apollo in /Users/main/apollo-angular-reproduction/node_modules/kamilkisiela-apollo-angular/Apollo.d.ts: (?). This will become an error in Angular v5.x`

**Comment by kamilkisiela** [comment]
Thanks!

**Comment by 3nd** [comment]
Many thanks! when will this change be added to the npm apollo-angular? Will it be 13.2?

**Comment by intellix** [comment]
You can install these today with: `npm i github:apollographql/apollo-angular`

**Pull request merged**
