### PR TITLE
Expose ClientMap, ClientMapWrapper, ClientWrapper

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by Uter1007** [comment]
Would that fix the AOT Problems ?

**Comment by CaerusKaru** [comment]
@Uter1007 AOT problems persist even with this PR

**Comment by Uter1007** [comment]
:-(

**Comment by CaerusKaru** [comment]
@Uter1007 AOT issues resolved by #364. You can use it in your project by running the following command (assuming you're using npm5):

`npm i github:CaerusKaru/apollo-angular#aot`

**Pull request merged**
