### PR TITLE
fix(link-http): Replace Array.includes with Array.indexOf

### LINKED ISSUE #407: Object [object Array] has no method 'includes'
Hello there,

I apologise if this is not the right place for this issue, but I'm not sure what else to do, I'm asking here because the error happens in `apollo-angular`'s code.

I'm using `apollo-angular` in my Ionic app, and it works fine on Browser and iOS platforms, but in Android I get this error:

```
Error: Network error: Object [object Array] has no method 'includes'
```

The request to the server goes through just fine, this error when it gets the response back.

This is the relevant code:

```ts
  private currentUser(cb) {
    this.apollo.query({
      query: gql`${this.currentUserQuery()}`
    }).subscribe(
      (res:any) => cb(res.data.user),
      (data) => this.error = data
    );
  }
```

I've tried to include `Array.prototype.includes` to my `.tsconfig.json`, but without success.

I've also tried to use es7 in a lot of ways by modifying `.tsconfig.json`, also without success.

Searching in this project, I'm only able to find [this instance](https://github.com/apollographql/apollo-angular/blob/0c1a68ba4f1faada19978c962cbe497a206336ed/packages/apollo-angular-link-http/src/HttpLink.ts#L69) of `.includes`.

Does anyone have any input that could help me get through this?

fwiw this is my `.tsconfig.json`

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

### PR DESCRIPTION
**Pull request by kamilkisiela**
Many browsers does not support it

Fixes #407

### CODE REVIEW

**Comment by rafbgarcia** [comment]
Thanks

**Comment by intellix** [comment]
Aren't these just getting transpiled down from TypeScript? :)

**Comment by kamilkisiela** [comment]
@intellix nope

**Comment by rafbgarcia** [comment]
@kamilkisiela do you know when a new release will be made to include this fix?

Thanks

**Comment by kamilkisiela** [comment]
Probably, in 2 hours

**Comment by kamilkisiela** [comment]
Published as v1.0.1

**Pull request merged**
