### PR TITLE
Don't reuse options object for mutate and query

### PR DESCRIPTION
**Pull request by Problematic**
Starting in 0.13.1, the options map passed to queries/mutations will be reused in some cases. In the case of queries, this causes errors, as the Apollo client first checks and throws if `options.notifyOnNetworkStatusChange` is not undefined, and then sets the option to false (https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L640-L645), so that it throws when reused. Simply spreading the options map into a new object resolves the problem.

### CODE REVIEW

**Comment by Problematic** [comment]
This is a showstopping issue for us; what else remains to be done so that a new release can be cut with this fix?

**Comment by irietek** [comment]
I'm stuck with this issue as well. Any chance we can get this fix merged in soon? Please and Thank You!

**Comment by infinitflow** [comment]
I have the same issue and tested this fix works. Any progress towards merging it would be greatly appreciated. Thank you

**Comment by kamilkisiela** [comment]
@Problematic could you add it also to the `CHANGELOG.md`?

**Comment by Problematic** [comment]
Done!

**Comment by Problematic** [comment]
Any updates here?

**Comment by infinitflow** [comment]
We are getting closer to merge!

**Comment by dflor003** [comment]
This is messing me up as well! Is this PR getting merged soon?

**Comment by johnrjj** [comment]
👍

**Comment by kamilkisiela** [comment]
You can check out the preview of 1.0 at #377

**Comment by Problematic** [comment]
Two things. First, he 1.0 preview doesn't appear to have this fix in it, and so will potentially have the same problems. And second, with the breaking API changes, I'm not sure we'll be able to consume it immediately. 

Can this PR be merged as a patch-level release in the 0.13 line, or is there additional work that needs to be done to make that possible?

**Comment by kamilkisiela** [comment]
@Problematic I will push a new version today. Could you create a test for it? If not, I'll probably do it before releasing v0.13.3.

**Comment by Problematic** [comment]
Yep, I'll start on that now.

**Comment by Problematic** [comment]
@kamilkisiela I'm unfamiliar with netlify; have I broken something?

**Comment by kamilkisiela** [comment]
@Problematic Released as [v0.13.3](https://github.com/apollographql/apollo-angular/releases/tag/0.13.3)

**Comment by Problematic** [comment]
Thank you!

**Pull request merged**
