### PR TITLE
[WIP] 1.0

### PR DESCRIPTION
**Pull request by kamilkisiela**
**Get to know the new API:**
- [Docs](https://deploy-preview-377--apollo-angular-docs.netlify.com/)
- [Migration guide](https://github.com/apollographql/apollo-angular/blob/1.0/Migration.md)
- [Changelog](https://github.com/apollographql/apollo-angular/blob/1.0/packages/apollo-angular/CHANGELOG.md)

Let me know what you think.

It's the right time to make suggestions, share ideas etc.

Latest *(31.10.2017)*:
 - `apollo-angular@1.0.0-beta.2`
 - `apollo-angular-link-http@1.0.0-beta.5`

You can **play with it** *(31.10.2017)*:
https://stackblitz.com/edit/simple-apollo-angular-example

---

**NativeScript** app:
https://github.com/kamilkisiela/apollo-angular-nativescript

**SSR** + Store Rehydration:
https://github.com/kamilkisiela/apollo-angular-ssr

Apollo as **State** Manager
https://stackblitz.com/edit/apollo-angular-state

### CODE REVIEW

**Comment by kamilkisiela** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.ts`.
  </td>
    </tr>
  </tbody>
</table>



## Error SyntaxError
```
Unexpected token import
dangerfile.ts:2
import * as fs from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at requireFromString (/home/travis/build/apollographql/apollo-angular/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:96:21)
    at step (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:3:12)
```
### Dangerfile
```
75| 
76|   const hasAppChanges = modifiedAppFiles.length > 0;
77| 
78|   const testChanges = modifiedAppFiles.filter(filepath =>
79|     filepath.includes('test'),
------------^
80|   );
81|   const hasTestChanges = testChanges.length > 0;
82| 
83|   // Warn when there is a big PR
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by kamilkisiela** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.ts`.
  </td>
    </tr>
  </tbody>
</table>



## Error SyntaxError
```
Unexpected token import
dangerfile.ts:2
import * as fs from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at requireFromString (/home/travis/build/apollographql/apollo-angular/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:96:21)
    at step (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:3:12)
```
### Dangerfile
```
75| 
76|   const hasAppChanges = modifiedAppFiles.length > 0;
77| 
78|   const testChanges = modifiedAppFiles.filter(filepath =>
79|     filepath.includes('test'),
------------^
80|   );
81|   const hasTestChanges = testChanges.length > 0;
82| 
83|   // Warn when there is a big PR
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by kamilkisiela** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error SyntaxError
```
Unexpected token import
dangerfile.js:2
import * as fs from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at requireFromString (/home/travis/build/apollographql/apollo-angular/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:96:21)
    at step (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:3:12)
```
### Dangerfile
```
75| 
76|   const hasAppChanges = modifiedAppFiles.length > 0;
77| 
78|   const testChanges = modifiedAppFiles.filter(filepath =>
79|     filepath.includes('test'),
------------^
80|   );
81|   const hasTestChanges = testChanges.length > 0;
82| 
83|   // Warn when there is a big PR
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by kamilkisiela** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error TypeError
```
danger.warn is not a function
TypeError: danger.warn is not a function
    at Object.<anonymous> (dangerfile.js:77:12)
    at Module._compile (module.js:612:30)
    at requireFromString (/home/travis/build/apollographql/apollo-angular/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:96:21)
    at step (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at Object.runDangerfileEnvironment (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:66:12)
```
### Dangerfile
```
72|   if (pr.body.length === 0) {
73|     danger.fail('Please add a description to your PR.');
74|   }
75| 
76|   const hasAppChanges = modifiedAppFiles.length > 0;
--------------^
77| 
78|   const testChanges = modifiedAppFiles.filter(filepath =>
79|     includes(filepath, 'test'),
80|   );
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by kamilkisiela** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error TypeError
```
danger.warn is not a function
TypeError: danger.warn is not a function
    at Object.<anonymous> (dangerfile.js:76:12)
    at Module._compile (module.js:612:30)
    at requireFromString (/home/travis/build/apollographql/apollo-angular/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:96:21)
    at step (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at Object.runDangerfileEnvironment (/home/travis/build/apollographql/apollo-angular/node_modules/danger/distribution/runner/runners/inline.js:66:12)
```
### Dangerfile
```
71|   if (pr.body.length === 0) {
72|     danger.fail('Please add a description to your PR.');
73|   }
74| 
75|   const hasAppChanges = modifiedAppFiles.length > 0;
--------------^
76| 
77|   const testChanges = modifiedAppFiles.filter(filepath =>
78|     includes(filepath, 'test'),
79|   );
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by kamilkisiela** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: Error

```sh
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at getBabelRC (/home/travis/build/apollographql/apollo-angular/node_modules/babel-jest/build/index.js:53:41)
    at Object.getCacheKey (/home/travis/build/apollographql/apollo-angular/node_modules/babel-jest/build/index.js:90:14)
    at ScriptTransformer._getCacheKey (/home/travis/build/apollographql/apollo-angular/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
    at ScriptTransformer._getFileCachePath (/home/travis/build/apollographql/apollo-angular/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
    at ScriptTransformer.transformSource (/home/travis/build/apollographql/apollo-angular/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
    at ScriptTransformer._transformAndBuildScript (/home/travis/build/apollographql/apollo-angular/node_modules/jest-runtime/build/ScriptTransformer.js:275:40)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Epenance** [comment]
Been playing with this the last few days and so far almost no issues, big props for making it work so well with most of the old API!

However, I think I'm doing it correct when i define my variables for my mutations, and from looking at the headers in my browser it would appear as if they are included but they dont seem to get attached to my query, which makes it complain.

You can see my code example here: http://jmp.sh/wu0RocY

And this is what i get back in my console when i try to run the query: GraphQL error: Variable "$email" of required type "String!" was not provided.

**Comment by kamilkisiela** [comment]
@Epenance Hi there! Thanks and that's great it works in your app.

I tried to reproduce same thing you have, which is a mutation + named client.
Here's the result:
https://stackblitz.com/edit/simple-apollo-angular-example-named

It seems to work.

**Comment by Epenance** [comment]
@kamilkisiela Thanks for the quick reply, I'm trying to investigate why it wont work on my end, tried to pretty much 1 to 1 copy your example and I'm still having issues. I'll get back when I know more of have given up on my life.

**Comment by kamilkisiela** [comment]
@Epenance try to make the same request but without Apollo. Same payload, same url etc. This way we could now if it's Apollo that causing an issue or the gql endpoint

**Comment by Epenance** [comment]
If i simply do it by putting it directly into the string like this it works: http://jmp.sh/BYE1GUA

**Comment by kamilkisiela** [comment]
@Epenance maybe the Apollo's Slack? Are you there? Same user handle as here, I have :yoda:

**Comment by kamilkisiela** [comment]
f520709 allows to type the operation variables

```ts
const addTodo = gql`
  mutation addTodo($text: String!) {
    addTodo(text: $text) {
      id
      text
    }
  }
`;

type Todo = {
  id: number;
  text: string;
};

type Mutation = {
  addTodo: Todo;
};

type Variables = {
  text: string;
};

apollo.mutation<Mutation, Variables>({
  mutation,
  variables: { } // TypeScript will warn you that `text` prop is required
}).subscribe();


apollo.mutation<Mutation, Variables>({
  mutation,
  variables: { text: 'Release Apollo' } // TypeScript gives a green light
}).subscribe();
```

**Comment by jakobwilkenson** [comment]
Hi. I know this is an impossible question but how far from production ready to you think this is? I currently have a meteor/ionic app that I'm trying to port off meteor (the meteor/angular integration is too painful) and Apollo seems like a great alternative, but only if it integrates with Angular. This project seems like the perfect solution.

Thanks

**Comment by Epenance** [comment]
@jakobwilkenson I've been testing it for roughly a week now, and the issue i had above turned out to have nothing to do with this lib, but rather my backend.

I'd say its very mature, I've had very little issues with it, mainly just documentation missing but @kamilkisiela is very good at answering on Slack and has been a tremendous help to me.

**Comment by jakobwilkenson** [comment]
@Epenance Thanks. I've started playing around with it and I got the stackblitz example working with no problem but as soon as I add it to an ionic project it stops working. When I call query/watchquery it doesn't even make a server request. I'll try to debug it and ping @kamilkisiela if I get stuck

**Comment by kamilkisiela** [comment]
I'm finishing an ApolloCache that is based on `@ngrx/store` and `@ngrx/entity` so you can use Apollo with ngrx based apps.

**Comment by kamilkisiela** [comment]
@jakobwilkenson I think the only part of the API that could be change in near future is the way we use headers in `apollo-angular-link-http`. I'm going to talk with few people about it and then after few reviews it could be shipped as a RC. 

When? I would say, it would be nice to release it as RC before AngularConnect or right after the event but I can't promise that.

This applies to `apollo-angular-link-http` and `apollo-angular` itself. `@ngrx/store` would have to wait to get into RC, it need more testing because it's such a new thing.

**Comment by jakobwilkenson** [comment]
@kamilkisiela Sounds good. I think I'll go forward and start porting my project then. Thanks!

**Comment by jzahka** [comment]
@kamilkisiela what are the benefits of using an ngrx based ApolloCache vs the standard in memory ApolloCache?

**Pull request merged**
