### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dotansimha**
@eitanfr  @tomermoshe @Urigo @kamilkisiela 

Updated apollo-client-rxjs to latest 0.6.0-rc.1. otherwise, it's impossible to use latest TypeScript compiler and latest angular-cli.

Also - updated some other deps and some minor fixes after updating

### CODE REVIEW

**Comment by kamilkisiela** [comment]
After merging this I can finish my two PRs, one that fixes SSR and other that puts modules into root directory so we can use `apollo-angular/Apollo` and so on.

**Comment by Urigo** [comment]
thank you so much @dotansimha !
@kamilkisiela let's get your two PRs ready before the new release?
by the way, @kamilkisiela why is apollo-client-rxjs in RC?

**Comment by kamilkisiela** [comment]
@Urigo I wasn't sure that it solves the issue for everyone

**Comment by Urigo** [comment]
released as `0.13.1`

**Comment by picosam** [comment]
Thank you both! @kamilkisiela you say you *weren't* sure... but now you are? 😄

**Comment by dotansimha** [comment]
@Urigo @kamilkisiela 
Also, @DxCx mentioned that we probably no longer need `apollo-client-rxjs` because apollo client support Observable now

**Pull request merged**
