### PR TITLE
fix(docs): corrected cacheResolver -> cacheRedirect

### LINKED ISSUE #715: fix(docs): cache redirects section incorrectly(?) calls for `cacheResolvers` property
In the cache updates section of the apollo-angular docs, cache redirects are discussed. Devs are instructed to implement cache redirects by [adding `cacheResolvers`](https://github.com/apollographql/apollo-angular/blob/master/docs/source/features/cache-updates.md#cache-redirects-with-cacheresolvers) to their `InMemoryCache` config like so:

> ```
> import { toIdValue } from 'apollo-utilities';
> import { InMemoryCache } from 'apollo-cache-inmemory';
> 
> const cache = new InMemoryCache({
>   cacheResolvers: {
>     Query: {
>       book: (_, args) => toIdValue(client.dataIdFromObject({ __typename: 'Book', id: args.id })),
>     },
>   },
> });
> ```

A) copy and pasting this code into VSCode indicates a type error, `InMemoryCache` doesn't expect it's config object to contain a `cacheResolvers` property.

B) [the docs section on cache redirects in the react apollo angular client](https://www.apollographql.com/docs/react/advanced/caching.html#cacheRedirect) instructs folks to add a `cacheRedirects` property (as oppose to a `cacheResolvers` property) to the `InMemoryCache` config to accomplish the same thing. Using that property doesn't result in a type error.

Unfortunately, I haven't gotten either method to work ([see S.O. issue](https://stackoverflow.com/questions/51423634/why-isnt-apollo-calling-my-cacheredirect-for-this-query)). I'm not sure if my problems are the result of a docs error or if the docs error is merely coincidental (or maybe there is no docs error and instead there is a type error).

### PR DESCRIPTION
**Pull request by thefliik**
fixes #715 

- also updated code snippets for current api

Used language from the [react Apollo Client docs](https://www.apollographql.com/docs/react/advanced/caching.html#cacheRedirect)

### CODE REVIEW

**Comment by thefliik** [comment]
Hey @kamilkisiela, so I signed it, but why are you asking me to sign a "meteor" CLA for an apollo project? The CLA begins with

>Thank you for contributing code to the Meteor project! 

But I haven't committed code the the Meteor project...

Looking through the `README.md` and `CONTRIBUTING.md`, I don't see any reference to meteor. Is this project owned by [Meteor](https://www.meteor.com/)?

**Comment by kamilkisiela** [comment]
That's the same company

**Comment by thefliik** [comment]
Gotcha

**Comment by kamilkisiela** [comment]
thank you, merged! :+1:

**Pull request merged**
